name: grinder
# This version must be updated in tandem with the lib/src/cli.dart version.
version: 0.7.0
description: Dart workflows, automated.

homepage: https://github.com/google/grinder.dart
author: Devon Carew <devoncarew@google.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  ansicolor: '>=0.0.9 <0.1.0'
  args: '>=0.10.0 <0.14.0'
  cli_util: '>=0.0.1 <0.1.0'
  glob: '>=1.0.0 <2.0.0'
  http_server: '>=0.9.0 <0.10.0'
  unscripted: '>=0.6.1+1 <0.7.0'
  which: '>=0.1.2 <0.2.0'

dev_dependencies:
  browser: any
  unittest: '^0.11.0'

executables:
  grind: grinder
